version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: tsed-demo/server:latest
    ports:
      - '8081:8081'
  mysql:
    image: mysql:8.0.28-oracle
    ports:
      - '3306:3306'
    environment:
      # MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      # MYSQL_USER: root
      # MYSQL_PASSWORD:
      MYSQL_DATABASE: blog
